"""create pantry_item

Revision ID: 3c5c3b5cd329
Revises: 941eea38b4ee
Create Date: 2026-06-25 23:57:13.643580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c5c3b5cd329'
down_revision: Union[str, Sequence[str], None] = '941eea38b4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_item',
    sa.Column('quantity_canonical', sa.Float(), nullable=False),
    sa.Column('display_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pantry_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pantry_item_ingredient_id'), ['ingredient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantry_item_ingredient_id'))

    op.drop_table('pantry_item')
    # ### end Alembic commands ###
