"""create ingredient

Revision ID: 941eea38b4ee
Revises: 
Create Date: 2026-06-23 23:56:07.470015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '941eea38b4ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measurement_type', sa.Enum('weight', 'volume', 'count', name='measurementtype'), nullable=False),
    sa.Column('default_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department', sa.Enum('produce', 'meat', 'dairy/eggs', 'bakery', 'frozen', 'canned', 'baking', 'snacks', 'beverages', 'other', name='department'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_name'))

    op.drop_table('ingredient')
    # ### end Alembic commands ###
